
	<br clear="all" />
	<div id="footer">
		<center>ISSN 1927-1417 (Print) ISSN 1927-1425 (Online)</center>
		<center>Copyright 2011 <i>The Waterloo Mathematics Review</i></center>
		<center>Generously supported by the <a href="http://www.student.math.uwaterloo.ca/~mefcom/home">Mathematics Endowment Fund</a>, the <a href="http://mathsoc.uwaterloo.ca/">Mathematics Society</a>, <a href="http://mathnews.uwaterloo.ca">mathNEWS</a>, and the <a href="http://math.uwaterloo.ca/">Faculty of Mathematics</a></center>
	</div>
</div>
</html>
