<html>
<head>
<title>The Waterloo Mathematics Review</title>

<link href="styles-site.css" type="text/css" rel="stylesheet" media="all" />
<link href='http://fonts.googleapis.com/css?family=Droid+Serif:regular,italic,bold&subset=latin' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold&subset=latin' rel='stylesheet' type='text/css'>

<meta name="google-site-verification" content="3M79RFMQXwkETxL3hMievZ04EregDgz0VAv8Z7QDd5U" />

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19536449-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>

<body>

<div id="outercontainer">
<div id="container">

	<div id="header">
		<img src="mc.png" width="298px" border=0 valign="bottom" alt="Math and Computer Building" />
		<div id="logo">
		<a href="index.html">The Waterloo Mathematics Review</a>
		</div>
	</div>
