	<div id="sidebar" class="column">
		<br/>
		<div class="navlink" style="border-top: solid 1px #808080;"><a href="/index.html" class="navigation">Home</a></div>
		<div class="navlink"><a href="/archive/voli/2/index.html">Current Issue</a></div>
		<div class="navlink"><a href="/archive/index.html">Past Issues</a></div>
		<div class="navlink"><a href="/submissions.html" class="navigation">Submissions</a></div>
		<div class="navlink"><a href="/about.html" class="navigation">About</a></div>
		<br />
		<div class="rightcontent">
		<strong>The Waterloo Mathematics Review</strong><br />
		Faculty of Mathematics<br />
		University of Waterloo<br />
		200 University Ave. West<br />
		Waterloo, Ontario, N2L 3G1<br/><br/>

		<strong>Editorial Contact:</strong><br />
		<a href="mailto:editor@mathreview.uwaterloo.ca">editor@mathreview.uwaterloo.ca</a>
		</div>
	</div>
